# Generated by Django 3.2.8 on 2022-10-19 07:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 10, 19, 7, 32, 54, 617294))),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 10, 19, 7, 32, 54, 617713))),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debateApp.role')),
            ],
        ),
    ]
