# Generated by Django 3.2.8 on 2022-10-19 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debateApp', '0006_auto_20221019_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='is_tarminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 10, 34, 24, 10021)),
        ),
        migrations.AlterField(
            model_name='debatelist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 10, 34, 24, 8289)),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 10, 34, 24, 7097)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 10, 34, 24, 7693)),
        ),
    ]
