# Generated by Django 3.2.8 on 2022-10-28 07:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debateApp', '0007_auto_20221019_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildClass',
            fields=[
                ('debate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='debateApp.debate')),
            ],
            bases=('debateApp.debate',),
        ),
        migrations.AlterField(
            model_name='debate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 7, 41, 32, 475319)),
        ),
        migrations.AlterField(
            model_name='debatelist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 7, 41, 32, 473974)),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 7, 41, 32, 473191)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 7, 41, 32, 473574)),
        ),
    ]
